<div>
	<h1>Master Address</h1>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/towns">Towns</a></li>
		<li><a href="<?php echo BASE_URL; ?>/townships">Townships</a></li>
		<li><a href="<?php echo BASE_URL; ?>/plats">Plats</a></li>
		<li><a href="<?php echo BASE_URL; ?>/precincts">Precincts</a></li>
		<li><a href="<?php echo BASE_URL; ?>/jurisdictions">Jurisdictions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/buildingTypes">Building Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/streetStatuses">Street Statuses</a></li>
	</ul>
</div>
