create or replace force view locations_all (
location_id, location_type_id, street_address_id,
full_street_name, full_street_address, full_street_address_sud,
subunit_id, mailable_flag, livable_flag, street_number, street_id,
address_type, tax_jurisdiction, jurisdiction_id, gov_jur_id, township_id,
section, quarter_section, subdivision_id, plat_id, plat_lot_number, street_address_2,
city, state, zip, zipplus4, census_block_fips_code,
state_plane_x_coordinate, state_plane_y_coordinate, latitude, longitude,
address_notes, street_direction_code, post_direction_suffix_code, town_id, status_code,
street_notes, street_name, street_type_suffix_code, street_name_type,
effective_start_date, effective_end_date, street_name_notes,
subunit_type, subunit, subunit_notes,
loc_active_flag, location, address_status_code, address_status,
location_status_code, location_status, subunit_status_code, subunit_status, incity)
as
select location_id,
	location_type_id,
	street_address_id,
	upper(full_street_name) as full_street_name,
	upper(full_street_address) as full_street_address,
	upper(full_street_address_sud) as full_street_address_sud,
	subunit_id,
	mailable_flag,
	livable_flag,
	upper(street_number) as street_number,
	street_id,
	address_type,
	upper(tax_jurisdiction) as tax_jurisdiction,
	jurisdiction_id,
	gov_jur_id,
	township_id,
	section,
	upper(quarter_section) as quarter_section,
	subdivision_id,
	plat_id,
	plat_lot_number,
	upper(street_address_2) as street_address_2,
	upper(city) as city,
	upper(state) as state,
	zip,
	zipplus4,
	census_block_fips_code,
	state_plane_x_coordinate,
	state_plane_y_coordinate,
	latitude,
	longitude,
	address_notes,
	upper(street_direction_code) as street_direction_code,
	upper(post_direction_suffix_code) as post_direction_suffix_code,
	town_id,
	status_code,
	street_notes,
	upper(street_name) as street_name,
	upper(street_type_suffix_code) as street_type_suffix_code,
	upper(street_name_type) as street_name_type,
	effective_start_date,
	effective_end_date,
	street_name_notes,
	upper(subunit_type) as subunit_type,
	upper(subunit) as subunit,
	subunit_notes,
	loc_active_flag,
	location,
	address_status_code,
	address_status,
	location_status_code,
	location_status,
	subunit_status_code,
	subunit_status,
	incity
from locations_all_v;