-- Old One

  CREATE MATERIALIZED VIEW "CUBS"."LOCATIONS_ALL_S"
  ORGANIZATION HEAP PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2621440 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CUBSD"
  BUILD IMMEDIATE
  USING INDEX
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT TRUNC(SYSDATE+1) + (6/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT
          loc.location_id,
          loc.location_type_id,
          loc.street_address_id,
          loc.subunit_id,
          loc.mailable_flag,
          loc.livable_flag,
          RTRIM(names.street_direction_code) street_direction_code,
          RTRIM(street.post_direction_suffix_code) post_direction_suffix_code,
          street.town_id,
          street.status_code,
          RTRIM(street.notes) street_notes,
          RTRIM(names.street_name) street_name,
          RTRIM(names.street_type_suffix_code) street_type_suffix_code,
          RTRIM(names.street_name_type) street_name_type,
          names.effective_start_date,
          names.effective_end_date,
          RTRIM(names.notes) street_name_notes,
          RTRIM(suds.sudtype) sudtype,
          RTRIM(suds.street_subunit_identifier) street_subunit_identifier,
          RTRIM(suds.notes) subunit_notes,
          RTRIM(NVL(addr.street_number, addr.street_address_2)) street_number,
          addr.street_id,
          addr.address_type,
          addr.tax_jurisdiction,
          addr.jurisdiction_id,
          addr.gov_jur_id,
          addr.township_id,
          addr.section,
          addr.quarter_section,
          addr.subdivision_id,
          addr.plat_id,
          addr.plat_lot_number,
          addr.street_address_2,
          RTRIM(addr.city) city,
          RTRIM(addr.state) state,
          addr.zip,
          addr.zipplus4,
          addr.census_block_fips_code,
          addr.state_plane_x_coordinate,
          addr.state_plane_y_coordinate,
          addr.latitude,
          addr.longitude,
          RTRIM(addr.notes) address_notes
     FROM
          eng.address_location@earthgis.world loc,
          eng.mast_address@earthgis.world addr,
          eng.mast_street@earthgis.world street,
          eng.mast_street_names@earthgis.world names,
          eng.mast_address_subunits@earthgis.world suds
    WHERE
          loc.street_address_id = addr.street_address_id
      AND loc.active = 'Y'
      AND addr.street_id = street.street_id
      AND street.street_id = names.street_id
      AND names.street_name_type = 'STREET'
      AND loc.subunit_id = suds.subunit_id(+)
UNION ALL
   SELECT LOCATION_ID,
		LOCATION_TYPE_ID,
		STREET_ADDRESS_ID,
		SUBUNIT_ID,
		MAILABLE_FLAG,
		LIVABLE_FLAG,
		STREET_DIRECTION_CODE,
		POST_DIRECTION_SUFFIX_CODE,
		TOWN_ID,
		STATUS_CODE,
		STREET_NOTES,
		STREET_NAME,
		STREET_TYPE_SUFFIX_CODE,
		STREET_NAME_TYPE,
		EFFECTIVE_START_DATE,
		EFFECTIVE_END_DATE,
		STREET_NAME_NOTES,
		SUDTYPE,
		STREET_SUBUNIT_IDENTIFIER,
		SUBUNIT_NOTES,
		STREET_NUMBER,
		STREET_ID,
		ADDRESS_TYPE,
		TAX_JURISDICTION,
		JURISDICTION_ID,
		GOV_JUR_ID,
		TOWNSHIP_ID,
		SECTION,
		QUARTER_SECTION,
		SUBDIVISION_ID,
		PLAT_ID,
		PLAT_LOT_NUMBER,
		STREET_ADDRESS_2,
		CITY,
		STATE,
		ZIP,
		ZIPPLUS4,
		CENSUS_BLOCK_FIPS_CODE,
		STATE_PLANE_X_COORDINATE,
		STATE_PLANE_Y_COORDINATE,
		LATITUDE,
		LONGITUDE,
		ADDRESS_NOTES
 FROM cubs.locations_unmatched
UNION ALL
   SELECT location_id,
          'UNKNOWN'	location_type_id,
          0			street_address_id,
          TO_NUMBER(NULL)	subunit_id,
          0			mailable_flag,
          0			livable_flag,
          NULL		street_direction_code,
          NULL		post_direction_suffix_code,
          TO_NUMBER(NULL)	town_id,
          1			status_code,
          NULL		street_notes,
          'TEMPORARY METER LOCATION'	STREET_NAME,
          'BYP'		street_type_suffix_code,
          'STREET'	street_name_type,
          TO_DATE(NULL)	effective_start_date,
          TO_DATE(NULL)	effective_end_date,
          NULL		street_name_notes,
          NULL		sudtype,
          NULL		street_subunit_identifier,
          NULL		subunit_notes,
          SUBSTR(meter_id,1,20)	street_number,
          TO_NUMBER(NULL)	street_id,
          'STREET'	address_type,
          NULL		tax_jurisdiction,
          1			jurisdiction_id,
          1			gov_jur_id,
          TO_NUMBER(NULL)	township_id,
          NULL		section,
          NULL		quarter_section,
          TO_NUMBER(NULL)	subdivision_id,
          TO_NUMBER(NULL)	plat_id,
          TO_NUMBER(NULL)	plat_lot_number,
          NULL		street_number_2,
          'BLOOMINGTON'	city,
          'IN'		state,
          '47401'	zip,
          '0000'	zipplus4,
          NULL		census_block_fips_code,
          TO_NUMBER(NULL)	state_plane_x_coordinate,
          TO_NUMBER(NULL)	state_plane_y_coordinate,
          TO_NUMBER(NULL)	latitude,
          TO_NUMBER(NULL)	longitude,
          NULL		address_notes
   FROM	cubs.temporary_meter_locations
;



-- New One

create materialized view locations_all_s
tablespace "CUBSD"
build immediate
using index
refresh complete on demand start with sysdate+0 next trunc(sysdate+1) + (6/24)
using default local rollback segment
disable query rewrite
as select
	loc.location_id,
	loc.location_type_id,
	loc.street_address_id,
	loc.subunit_id,
	decode(loc.mailable_flag,'yes',1,'no',0,'unknown',NULL,NULL) as mailable_flag,
	decode(loc.livable_flag,'yes',1,'no',0,'unknown',NULL,NULL) as livable_flag,
	upper(RTRIM(names.street_direction_code)) as street_direction_code,
	upper(RTRIM(street.post_direction_suffix_code)) as post_direction_suffix_code,
	street.town_id,
	street.status_code,
	RTRIM(street.notes) as street_notes,
	upper(RTRIM(names.street_name)) as street_name,
	upper(RTRIM(names.street_type_suffix_code)) as street_type_suffix_code,
	upper(RTRIM(names.street_name_type)) as street_name_type,
	names.effective_start_date,
	names.effective_end_date,
	RTRIM(names.notes) as street_name_notes,
	upper(RTRIM(suds.sudtype)) as sudtype,
	upper(RTRIM(suds.street_subunit_identifier)) as street_subunit_identifier,
	RTRIM(suds.notes) as subunit_notes,
	upper(RTRIM(NVL(addr.street_number, addr.street_address_2))) as street_number,
	addr.street_id,
	upper(addr.address_type) as address_type,
	upper(addr.tax_jurisdiction) as tax_jurisdiction,
	addr.jurisdiction_id,
	addr.gov_jur_id,
	addr.township_id,
	addr.section,
	upper(addr.quarter_section) as quarter_section,
	addr.subdivision_id,
	addr.plat_id,
	addr.plat_lot_number,
	upper(addr.street_address_2) as street_address_2,
	upper(RTRIM(addr.city)) as city,
	upper(RTRIM(addr.state)) as state,
	to_char(addr.zip) as zip,
	addr.zipplus4,
	addr.census_block_fips_code,
	addr.state_plane_x_coordinate,
	addr.state_plane_y_coordinate,
	addr.latitude,
	addr.longitude,
	RTRIM(addr.notes) as address_notes
FROM
	eng.address_location@earthgis.world loc,
	eng.mast_address@earthgis.world addr,
	eng.mast_street@earthgis.world street,
	eng.mast_street_names@earthgis.world names,
	eng.mast_address_subunits@earthgis.world suds
WHERE
		loc.street_address_id = addr.street_address_id
	AND loc.active = 'Y'
	AND addr.street_id = street.street_id
	AND street.street_id = names.street_id
	AND names.street_name_type = 'STREET'
	AND loc.subunit_id = suds.subunit_id(+)
UNION ALL
SELECT LOCATION_ID,
	LOCATION_TYPE_ID,
	STREET_ADDRESS_ID,
	SUBUNIT_ID,
	MAILABLE_FLAG,
	LIVABLE_FLAG,
	STREET_DIRECTION_CODE,
	POST_DIRECTION_SUFFIX_CODE,
	TOWN_ID,
	STATUS_CODE,
	STREET_NOTES,
	STREET_NAME,
	STREET_TYPE_SUFFIX_CODE,
	STREET_NAME_TYPE,
	EFFECTIVE_START_DATE,
	EFFECTIVE_END_DATE,
	STREET_NAME_NOTES,
	SUDTYPE,
	STREET_SUBUNIT_IDENTIFIER,
	SUBUNIT_NOTES,
	STREET_NUMBER,
	STREET_ID,
	ADDRESS_TYPE,
	TAX_JURISDICTION,
	JURISDICTION_ID,
	GOV_JUR_ID,
	TOWNSHIP_ID,
	SECTION,
	QUARTER_SECTION,
	SUBDIVISION_ID,
	PLAT_ID,
	to_char(PLAT_LOT_NUMBER) as plat_lot_number,
	STREET_ADDRESS_2,
	CITY,
	STATE,
	ZIP,
	ZIPPLUS4,
	CENSUS_BLOCK_FIPS_CODE,
	STATE_PLANE_X_COORDINATE,
	STATE_PLANE_Y_COORDINATE,
	LATITUDE,
	LONGITUDE,
	ADDRESS_NOTES
FROM cubs.locations_unmatched
UNION ALL
SELECT location_id,
		'UNKNOWN'	location_type_id,
		0			street_address_id,
		TO_NUMBER(NULL)	subunit_id,
		NULL			mailable_flag,
		NULL			livable_flag,
		NULL		street_direction_code,
		NULL		post_direction_suffix_code,
		TO_NUMBER(NULL)	town_id,
		1			status_code,
		NULL		street_notes,
		'TEMPORARY METER LOCATION'	STREET_NAME,
		'BYP'		street_type_suffix_code,
		'STREET'	street_name_type,
		TO_DATE(NULL)	effective_start_date,
		TO_DATE(NULL)	effective_end_date,
		NULL		street_name_notes,
		NULL		sudtype,
		NULL		street_subunit_identifier,
		NULL		subunit_notes,
		SUBSTR(meter_id,1,20)	street_number,
		TO_NUMBER(NULL)	street_id,
		'STREET'	address_type,
		NULL		tax_jurisdiction,
		1			jurisdiction_id,
		1			gov_jur_id,
		TO_NUMBER(NULL)	township_id,
		NULL		section,
		NULL		quarter_section,
		TO_NUMBER(NULL)	subdivision_id,
		TO_NUMBER(NULL)	plat_id,
		to_char(NULL)	plat_lot_number,
		NULL		street_number_2,
		'BLOOMINGTON'	city,
		'IN'		state,
		'47401'	zip,
		'0000'	zipplus4,
		NULL		census_block_fips_code,
		TO_NUMBER(NULL)	state_plane_x_coordinate,
		TO_NUMBER(NULL)	state_plane_y_coordinate,
		TO_NUMBER(NULL)	latitude,
		TO_NUMBER(NULL)	longitude,
		NULL		address_notes
FROM	cubs.temporary_meter_locations
;
