<div class="sidebar">
	<div class="titleBar">Admin</div>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/towns">Towns</a></li>
		<li><a href="<?php echo BASE_URL; ?>/townships">Townships</a></li>
		<li><a href="<?php echo BASE_URL; ?>/jurisdictions">Jurisdictions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/statuses">Status Codes</a></li>
		<li><a href="<?php echo BASE_URL; ?>/suffixes">Suffixes</a></li>
		<li><a href="<?php echo BASE_URL; ?>/districtTypes">District Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/placeTypes">Place Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/unitTypes">Unit Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/buildingTypes">Building Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/directions">Directions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/platTypes">Plat Types</a></li>
	</ul>
</div>