load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDRESS_LOCATION.txt' into table address_location fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_JURISDICTION_MASTER.txt' into table addr_jurisdiction_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_LOCATION_PURPOSE_MAST.txt' into table addr_location_purpose_mast fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_LOCATION_PURPOSES.txt' into table addr_location_purposes fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_LOCATION_RELATIONSHIPS.txt' into table addr_location_relationships fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_LOCATION_REL_TYPES_MAST.txt' into table addr_location_rel_types_mast fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.ADDR_LOCATION_TYPES_MASTER.txt' into table addr_location_types_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.GOVERNMENTAL_JURISDICTION_MAST.txt' into table governmental_jurisdiction_mast fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDR_ASSGN_HIST_TEMP.txt' into table mast_addr_assgn_hist_temp fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDR_ASSIGNMENT_CONTACT.txt' into table mast_addr_assignment_contact fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_ANNEXATION.txt' into table mast_address_annexation fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_ASSIGNMENT_HIST.txt' into table mast_address_assignment_hist fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_LOCATION_CHANGE.txt' into table mast_address_location_change fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_LOCATION_STATUS.txt' into table mast_address_location_status fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_SANITATION.txt' into table mast_address_sanitation fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_STATUS_LOOKUP.txt' into table mast_address_status_lookup fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_STATUS.txt' into table mast_address_status fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_SUBUNIT_STATUS.txt' into table mast_address_subunit_status fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS_SUBUNITS.txt' into table mast_address_subunits fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDRESS.txt' into table mast_address fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_ADDR_SUBUNIT_TYPES_MAST.txt' into table mast_addr_subunit_types_mast fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_ADDR_JURISDICTIONS.txt' into table mast_street_addr_jurisdictions fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_DIRECTION_MASTER.txt' into table mast_street_direction_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_GOV_JURISDICTIONS.txt' into table mast_street_gov_jurisdictions fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_NAMES.txt' into table mast_street_names fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_NAME_TYPE_MASTER.txt' into table mast_street_name_type_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_PLAT.txt' into table mast_street_plat fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_SECTION.txt' into table mast_street_section fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_STATE_ROAD.txt' into table mast_street_state_road fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_STATUS_LOOKUP.txt' into table mast_street_status_lookup fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_SUBDIVISION.txt' into table mast_street_subdivision fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_TOWNSHIPS.txt' into table mast_street_townships fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET.txt' into table mast_street fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.MAST_STREET_TYPE_SUFFIX_MASTER.txt' into table mast_street_type_suffix_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.PLAT_MASTER.txt' into table plat_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.QUARTER_SECTION_MASTER.txt' into table quarter_section_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.STATE_ROAD_MASTER.txt' into table state_road_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.SUBDIVISION_MASTER.txt' into table subdivision_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.SUBDIVISION_NAMES.txt' into table subdivision_names fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.TOWNSHIP_MASTER.txt' into table township_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.TOWNS_MASTER.txt' into table towns_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.TRASH_LARGE_ITEM_PICKUP_MASTER.txt' into table trash_large_item_pickup_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.TRASH_PICKUP_MASTER.txt' into table trash_pickup_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/ENG.TRASH_RECYCLE_WEEK_MASTER.txt' into table trash_recycle_week_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.ANNEXATIONS.txt' into table annexations fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.BUILDING_ADDRESS_LOCATION.txt' into table building_address_location fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.BUILDINGS_STATUS_LOOKUP.txt' into table buildings_status_lookup fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.BUILDINGS.txt' into table buildings fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.BUILDING_TYPES_MASTER.txt' into table building_types_master fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.LOCATIONS_CLASSES.txt' into table locations_classes fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.MAST_ADDRESS_PARCEL.txt' into table mast_address_parcel fields terminated by '|';
load data infile '/var/www/sites/master_address/scripts/data/GIS.PARCEL.txt' into table parcel fields terminated by '|';

-- Segments are seperate
load data infile '/var/www/sites/master_address/scripts/data/segments.txt' into table segments fields terminated by '|';

-- As of the last dump these were the problem ones.
select tag,count(*) as count from segments group by tag having count>1 order by count;

delete from segments where tag='ccl629' limit 1;
delete from segments where tag='ccl2151' limit 1;
delete from segments where tag='ccl1834' limit 1;
delete from segments where tag='rcl934' limit 1;
delete from segments where tag='ccl2371' limit 1;
