grant select,insert,update,delete,references on eng.address_location to master_address;
grant select,insert,update,delete,references on eng.addr_location_purpose_mast to master_address;
grant select,insert,update,delete,references on eng.addr_location_purposes to master_address;
grant select,insert,update,delete,references on eng.addr_location_rel_types_mast to master_address;
grant select,insert,update,delete,references on eng.addr_location_relationships to master_address;
grant select,insert,update,delete,references on eng.addr_location_types_master to master_address;
grant select,insert,update,delete,references on eng.governmental_jurisdiction_mast to master_address;
grant select,insert,update,delete,references on eng.mast_addr_assignment_contact to master_address;
grant select,insert,update,delete,references on eng.mast_addr_subunit_types_mast to master_address;
grant select,insert,update,delete,references on eng.mast_address to master_address;
grant select,insert,update,delete,references on eng.mast_address_annexation to master_address;
grant select,insert,update,delete,references on eng.mast_address_assignment_hist to master_address;
grant select,insert,update,delete,references on eng.mast_address_location_change to master_address;
grant select,insert,update,delete,references on eng.mast_address_location_status to master_address;
grant select,insert,update,delete,references on eng.mast_address_sanitation to master_address;
grant select,insert,update,delete,references on eng.mast_address_status to master_address;
grant select,insert,update,delete,references on eng.mast_address_status_lookup to master_address;
grant select,insert,update,delete,references on eng.mast_address_subunit_status to master_address;
grant select,insert,update,delete,references on eng.mast_address_subunits to master_address;
grant select,insert,update,delete,references on eng.mast_street to master_address;
grant select,insert,update,delete,references on eng.mast_street_addr_jurisdictions to master_address;
grant select,insert,update,delete,references on eng.mast_street_direction_master to master_address;
grant select,insert,update,delete,references on eng.mast_street_gov_jurisdictions to master_address;
grant select,insert,update,delete,references on eng.mast_street_name_type_master to master_address;
grant select,insert,update,delete,references on eng.mast_street_names to master_address;
grant select,insert,update,delete,references on eng.mast_street_plat to master_address;
grant select,insert,update,delete,references on eng.mast_street_section to master_address;
grant select,insert,update,delete,references on eng.mast_street_status_lookup to master_address;
grant select,insert,update,delete,references on eng.mast_street_subdivision to master_address;
grant select,insert,update,delete,references on eng.mast_street_townships to master_address;
grant select,insert,update,delete,references on eng.mast_street_type_suffix_master to master_address;
grant select,insert,update,delete,references on eng.plat_master to master_address;
grant select,insert,update,delete,references on eng.quarter_section_master to master_address;
grant select,insert,update,delete,references on eng.state_road_master to master_address;
grant select,insert,update,delete,references on eng.subdivision_master to master_address;
grant select,insert,update,delete,references on eng.subdivision_names to master_address;
grant select,insert,update,delete,references on eng.towns_master to master_address;
grant select,insert,update,delete,references on eng.township_master to master_address;
grant select,insert,update,delete,references on eng.trash_pickup_master to master_address;
grant select,insert,update,delete,references on eng.trash_recycle_week_master to master_address;

grant select on eng.address_status_code_seq to master_address;
grant select on eng.address_status_id_seq to master_address;
grant select on eng.contact_id_s to master_address;
grant select on eng.direction_id_seq to master_address;
grant select on eng.gov_jur_id_s to master_address;
grant select on eng.jurisdiction_id_s to master_address;
grant select on eng.location_change_id_s to master_address;
grant select on eng.location_id_s to master_address;
grant select on eng.location_purpose_id_s to master_address;
grant select on eng.location_status_id_seq to master_address;
grant select on eng.plat_id_s to master_address;
grant select on eng.street_address_id_s to master_address;
grant select on eng.street_id_s to master_address;
grant select on eng.street_names_id_s to master_address;
grant select on eng.street_name_type_id_s to master_address;
grant select on eng.street_status_code_seq to master_address;
grant select on eng.subdivision_id_s to master_address;
grant select on eng.subdivision_name_id_s to master_address;
grant select on eng.subunit_id_s to master_address;
grant select on eng.subunit_status_id_seq to master_address;
grant select on eng.subunit_type_id_s to master_address;
grant select on eng.suffix_id_seq to master_address;
grant select on eng.town_id_s to master_address;
grant select on eng.township_id_s to master_address;




create synonym master_address.address_location for eng.address_location;
create synonym master_address.addr_location_purpose_mast for eng.addr_location_purpose_mast;
create synonym master_address.addr_location_purposes for eng.addr_location_purposes;
create synonym master_address.addr_location_rel_types_mast for eng.addr_location_rel_types_mast;
create synonym master_address.addr_location_relationships for eng.addr_location_relationships;
create synonym master_address.addr_location_types_master for eng.addr_location_types_master;
create synonym master_address.governmental_jurisdiction_mast for eng.governmental_jurisdiction_mast;
create synonym master_address.mast_addr_assignment_contact for eng.mast_addr_assignment_contact;
create synonym master_address.mast_addr_subunit_types_mast for eng.mast_addr_subunit_types_mast;
create synonym master_address.mast_address for eng.mast_address;
create synonym master_address.mast_address_annexation for eng.mast_address_annexation;
create synonym master_address.mast_address_assignment_hist for eng.mast_address_assignment_hist;
create synonym master_address.mast_address_location_change for eng.mast_address_location_change;
create synonym master_address.mast_address_location_status for eng.mast_address_location_status;
create synonym master_address.mast_address_sanitation for eng.mast_address_sanitation;
create synonym master_address.mast_address_status for eng.mast_address_status;
create synonym master_address.mast_address_status_lookup for eng.mast_address_status_lookup;
create synonym master_address.mast_address_subunit_status for eng.mast_address_subunit_status;
create synonym master_address.mast_address_subunits for eng.mast_address_subunits;
create synonym master_address.mast_street for eng.mast_street;
create synonym master_address.mast_street_addr_jurisdictions for eng.mast_street_addr_jurisdictions;
create synonym master_address.mast_street_direction_master for eng.mast_street_direction_master;
create synonym master_address.mast_street_gov_jurisdictions for eng.mast_street_gov_jurisdictions;
create synonym master_address.mast_street_name_type_master for eng.mast_street_name_type_master;
create synonym master_address.mast_street_names for eng.mast_street_names;
create synonym master_address.mast_street_plat for eng.mast_street_plat;
create synonym master_address.mast_street_section for eng.mast_street_section;
create synonym master_address.mast_street_state_road for eng.mast_street_state_road;
create synonym master_address.mast_street_status_lookup for eng.mast_street_status_lookup;
create synonym master_address.mast_street_subdivision for eng.mast_street_subdivision;
create synonym master_address.mast_street_townships for eng.mast_street_townships;
create synonym master_address.mast_street_type_suffix_master for eng.mast_street_type_suffix_master;
create synonym master_address.plat_master for eng.plat_master;
create synonym master_address.quarter_section_master for eng.quarter_section_master;
create synonym master_address.subdivision_master for eng.subdivision_master;
create synonym master_address.subdivision_names for eng.subdivision_names;
create synonym master_address.towns_master for eng.towns_master;
create synonym master_address.township_master for eng.township_master;
create synonym master_address.trash_pickup_master for eng.trash_pickup_master;
create synonym master_address.trash_recycle_week_master for eng.trash_recycle_week_master;

create synonym master_address.address_status_code_seq for eng.address_status_code_seq;
create synonym master_address.address_status_id_seq for eng.address_status_id_seq;
create synonym master_address.contact_id_s for eng.contact_id_s;
create synonym master_address.direction_id_seq for eng.direction_id_seq;
create synonym master_address.gov_jur_id_s for eng.gov_jur_id_s;
create synonym master_address.location_change_id_s for eng.location_change_id_s;
create synonym master_address.location_id_s for eng.location_id_s;
create synonym master_address.location_purpose_id_s for eng.location_purpose_id_s;
create synonym master_address.location_status_id_seq for eng.location_status_id_seq;
create synonym master_address.plat_id_s for eng.plat_id_s;
create synonym master_address.street_address_id_s for eng.street_address_id_s;
create synonym master_address.street_id_s for eng.street_id_s;
create synonym master_address.street_names_id_s for eng.street_names_id_s;
create synonym master_address.street_name_type_id_s for eng.street_name_type_id_s;
create synonym master_address.street_status_code_seq for eng.street_status_code_seq;
create synonym master_address.subdivision_id_s for eng.subdivision_id_s;
create synonym master_address.subdivision_name_id_s for eng.subdivision_name_id_s;
create synonym master_address.subunit_id_s for eng.subunit_id_s;
create synonym master_address.subunit_status_id_seq for eng.subunit_status_id_seq;
create synonym master_address.subunit_type_id_s for eng.subunit_type_id_s;
create synonym master_address.suffix_id_seq for eng.suffix_id_seq;
create synonym master_address.town_id_s for eng.town_id_s;
create synonym master_address.township_id_s for eng.township_id_s;


grant select,insert,update,delete,references on gis.annexations to master_address;
grant select,insert,update,delete,references on gis.building_address_location to master_address;
grant select,insert,update,delete,references on gis.building_types_master to master_address;
grant select,insert,update,delete,references on gis.buildings to master_address;
grant select,insert,update,delete,references on gis.buildings_status_lookup to master_address;
grant select,insert,update,delete,references on gis.mast_address_parcel to master_address;
grant select,insert,update,delete,references on gis.parcel to master_address;
grant select,insert,update,delete,references on gis.precinct_address_location to master_address;
grant select,insert,update,delete,references on gis.voting_precincts to master_address;


grant select on gis.annexations_id_seq to master_address;
grant select on gis.building_id_s to master_address;
grant select on gis.building_type_id_s to master_address;
grant select on gis.buildings_status_code_seq to master_address;
grant select on gis.precinct_id_seq to master_address;


create synonym master_address.annexations for gis.annexations;
create synonym master_address.building_address_location for gis.building_address_location;
create synonym master_address.building_types_master for gis.building_types_master;
create synonym master_address.buildings for gis.buildings;
create synonym master_address.buildings_status_lookup for gis.buildings_status_lookup;
create synonym master_address.mast_address_parcel for gis.mast_address_parcel;
create synonym master_address.parcel for gis.parcel;
create synonym master_address.precinct_address_location for gis.precinct_address_location;
create synonym master_address.voting_precincts for gis.voting_precincts;


create synonym master_address.annexations_id_seq for gis.annexations_id_seq;
create synonym master_address.building_id_s for gis.building_id_s;
create synonym master_address.building_type_id_s for gis.building_type_id_s;
create synonym master_address.buildings_status_code_seq for gis.buildings_status_code_seq;
create synonym master_address.precinct_id_seq for gis.precinct_id_seq;



grant select on eng.mast_address_location_status to gis;
grant select on eng.mast_address_status to gis;
grant select on eng.mast_street_names to gis;

-- Extra user roles for Neptune
-- These grants cover stuff not necessarily pertaining to the master_address tables
create role address_editor;
grant insert,update on eng.address_location to address_editor;
grant insert,update on eng.addr_location_purposes to address_editor;
grant insert,update on eng.addr_location_purpose_mast to address_editor;
grant insert,update on eng.addr_location_relationships to address_editor;
grant insert,update on eng.addr_location_rel_types_mast to address_editor;
grant insert,update on eng.mast_address to address_editor;
grant insert,update on eng.mast_address_annexation to address_editor;
grant insert,update on eng.mast_address_location_change to address_editor;
grant insert,update on eng.mast_address_location_status to address_editor;
grant insert,update on eng.mast_address_sanitation to address_editor;
grant insert,update on eng.mast_address_status to address_editor;
grant insert,update on eng.mast_address_subunits to address_editor;
grant insert,update on eng.mast_address_subunit_status to address_editor;
grant insert,update on eng.mast_addr_assignment_contact to address_editor;
grant insert,update on eng.plat_master to address_editor;
grant insert,update on eng.subdivision_master to address_editor;
grant insert,update on eng.subdivision_names to address_editor;
grant insert,update on eng.mast_street to address_editor;
grant insert,update on eng.mast_street_direction_master to address_editor;
grant insert,update on eng.mast_street_names to address_editor;
grant insert,update on eng.mast_street_plat to address_editor;
grant insert,update on eng.mast_street_section to address_editor;
grant insert,update on eng.mast_street_state_road to address_editor;
grant insert,update on eng.mast_street_subdivision to address_editor;
grant insert,update on eng.mast_street_subdivision to address_editor;
grant insert,update on eng.mast_street_townships to address_editor;
grant insert,update on eng.mast_street_type_suffix_master to address_editor;

grant insert,update on gis.annexations to address_editor;
grant insert,update on gis.buildings to address_editor;
grant insert,update on gis.building_address_location to address_editor;
grant insert,update on gis.mast_address_parcel to address_editor;
grant insert,update on gis.parcel to address_editor;

grant insert,update on ueng.demolished_addresses to address_editor;
grant insert,update on ueng.mast_address to address_editor;
grant insert,update on ueng.meter_pit_link to address_editor;
grant insert,update on ueng.states to address_editor;
grant insert,update on ueng.street_types to address_editor;
grant insert,update on ueng.sud_types to address_editor;

grant execute on eng.create_corner_address to address_editor;
grant execute on eng.create_location_purpose to address_editor;
grant execute on eng.move_corner_address to address_editor;
grant execute on eng.reassign_address to address_editor;
grant execute on eng.retire_inactive_corner_address to address_editor;
grant execute on gis.create_luca_address to address_editor;

create role utilities_editor;
grant insert,update on eng.location to utilities_editor;
grant insert,update on eng.storm_basin to utilities_editor;
grant insert,update on eng.storm_compon to utilities_editor;
grant insert,update on eng.storm_cond to utilities_editor;
grant insert,update on eng.storm_desc to utilities_editor;
grant insert,update on eng.storm_image to utilities_editor;
grant insert,update on eng.storm_locate to utilities_editor;
grant insert,update on eng.storm_mat to utilities_editor;
grant insert,update on eng.storm_mat2 to utilities_editor;
grant insert,update on eng.storm_node to utilities_editor;
grant insert,update on eng.storm_node_compon to utilities_editor;
grant insert,update on eng.storm_node_prob to utilities_editor;
grant insert,update on eng.storm_offset to utilities_editor;
grant insert,update on eng.storm_pipe to utilities_editor;
grant insert,update on eng.storm_pipe_prob to utilities_editor;
grant insert,update on eng.storm_problem to utilities_editor;
grant insert,update on eng.storm_rcl to utilities_editor;
grant insert,update on eng.storm_shape to utilities_editor;
grant insert,update on eng.storm_source to utilities_editor;
grant insert,update on eng.storm_station to utilities_editor;
grant insert,update on eng.storm_station_loc to utilities_editor;
grant insert,update on eng.storm_surface to utilities_editor;
grant insert,update on eng.storm_sysname to utilities_editor;
grant insert,update on eng.storm_uppipe to utilities_editor;

grant insert,update on ueng.gis_revisions to utilities_editor;
grant insert,update on ueng.hydrants to utilities_editor;
grant insert,update on ueng.hydrant_tests to utilities_editor;
grant insert,update on ueng.manholes to utilities_editor;
grant insert,update on ueng.meters to utilities_editor;
grant insert,update on ueng.meter_install to utilities_editor;
grant insert,update on ueng.meter_locations to utilities_editor;
grant insert,update on ueng.meter_pits to utilities_editor;
grant insert,update on ueng.meter_tests to utilities_editor;
grant insert,update on ueng.pipe_diameters to utilities_editor;
grant insert,update on ueng.pipe_materials to utilities_editor;
grant insert,update on ueng.water_pipes to utilities_editor;
grant insert,update on ueng.water_pipe_diameters to utilities_editor;
grant insert,update on ueng.sewer_pipes to utilities_editor;
grant insert,update on ueng.wye_numbers to utilities_editor;
