<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url("/skins/default/skin.css");
	</style>
	<style type="text/css" media="print">@import url("/skins/default/print.css");</style>
	<script src="/functions.js" type="text/javascript"></script>
	<title>Master Address Database - City of Bloomington, Indiana</title>
</head>
<body>
<div id="banner">
	<h1><a href="<?php echo BASE_URL; ?>">Master Address Database</a></h1><h2>City of Bloomington, Indiana</h2>
</div>
