<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url("/skins/default/skin.css");
	</style>
	<style type="text/css" media="print">@import url("/skins/default/print.css");</style>
	<script src="/functions.js" type="text/javascript"></script>
	<?php if (isset($_POST)) { echo "<script type=\"text/javascript\">window.opener.location.reload();</script>"; } ?>
	<title>Master Address Database - City of Bloomington, Indiana</title>
</head>
<body>
